### PR TITLE
fix qos 0 messages persistance

### LINKED ISSUE #229: mongodb persistence is saving qos 0 packets
cleansession false, subscription topic is qos 1, i send some qos 0 packets and this are stored, but must be discarded. mongodb has store many irrelevant packets and performance down...

Levelup store has same problem...

http://www.hivemq.com/mqtt-essentials-part-7-persistent-session-queuing-messages/

So what will be stored in the session?

* Existence of a session, even if there are no subscriptions
* All subscriptions
*All messages in a Quality of Service (QoS) 1 or 2 flow, which are not confirmed by the client
*All new QoS 1 or 2 messages, which the client missed while it was offlne
*All received QoS 2 messages, which are not yet confirmed to the client

Mosquitto has a specific option for enabled it: 

Clean session / Durable connections

On connection, a client sets the "clean session" flag, which is sometimes also known as the "clean start" flag. If clean session is set to false, then the connection is treated as durable. This means that when the client disconnects, any subscriptions it has will remain and any subsequent QoS 1 or 2 messages will be stored until it connects again in the future. If clean session is true, then all subscriptions will be removed for the client when it disconnects.

queue_qos0_messages [ true | false ]

    Set to true to queue messages with QoS 0 when a persistent client is disconnected. These messages are included in the limit imposed by max_queued_messages. Defaults to false.

    Note that the MQTT v3.1 spec states that only QoS 1 and 2 messages should be saved in this situation so this is a non-standard option.

My mosca servers are slow and clients are fail because mosca send to many qos 0 packets after reconnect...

in packet collection:
 {
   "_id": ObjectId("5519aa844299b6b52fa8735a"),
   "client": "1100890580.990.1427234577275724365.7227479706",
   "packet": {
     "topic": "taxis\/990",
     "payload": "<Mongo Binary Data>",
     "messageId": NumberInt(5),
     "qos": NumberInt(0),
     "retain": false
  }
}	

thank you...

### PR DESCRIPTION
**Pull request by mazhack**
i try to fix #229

### CODE REVIEW

**Comment by mcollina** [comment]
Thanks a million, can you please add a test for those?

**Comment by mazhack** [comment]
review please... my test pass, websocket fail, i dont touch that, in my machine all test are fine.

File: lib/persistence/levelup.js [hunk 1]
```diff
@@ -67,6 +68,8 @@ var defaults = {
  *      It defaults to 1 hour.
  *  - `db`, the AbstractLevelDown implementation.
  *  - all other `levelup` otions.
+ *  - `store_qos0_messages` store messages with qos 0, default false
+ *     like mosquitto option 'queue_qos0_messages', non-standard option
```
Comment (mcollina) [inline lib/persistence/levelup.js]: can you please make the option camelCase?

File: lib/persistence/abstract.js [hunk 2]
```diff
@@ -52,6 +52,12 @@ AbstractPersistence.prototype.wire = function(server) {
   server.persistence = this;
 
   server.storePacket = function(packet, cb) {
+
+    // store qos 0 packets only if store_qos0_messages is true
+    if(packet.qos === 0 && packet.retain === false && ! that.options.store_qos0_messages){
+      return cb();
+    }
+
```
Comment (mcollina) [inline lib/persistence/abstract.js]: you should move this block later in the fuction, otherwise retained messages with QoS 0 will not be stored. It should be after: https://github.com/mazhack/mosca/blob/master/lib/persistence/abstract.js#L67-L70

**Comment by mcollina** [comment]
Thanks so much for this PR! I have added some comments, but it is generally good :).

**Comment by mazhack** [comment]
Retained messages are stored, i test it... I will make the option camel case in few das, now i am in vacations, i go back to work next Monday

**Comment by mazhack** [comment]
https://github.com/mazhack/mosca/blob/master/test/persistence/qos_0_persistence.js#L87-L128

**Comment by mazhack** [comment]
Ups, the test are wrong... Packet has qos 1, it must be qos 0, i will fix it next monday

**Comment by mazhack** [comment]
ups, fix for #231 merges with this PR, revert?

**Comment by mcollina** [comment]
Don't worry, that commit is ok, I get everything merged from here.

**Comment by mcollina** [comment]
I would prefer to have the tests inside https://github.com/mcollina/mosca/blob/master/test/persistence/abstract.js rather than in their own file, specific to Mongo.

**Comment by mazhack** [comment]
done, test for redis, mongo and leveldb.

**Comment by mcollina** [comment]
Released as 0.28.2.
